language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
    allow_failures:
        - php: hhvm
        
before_install:
    - composer self-update

install: composer update --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
