<?php

use PHPUnit\Framework\TestCase;

if (!class_exists('\PHPUnit\Framework\TestCase') && class_exists('\PHPUnit_Framework_TestCase')) {
    class_alias('\PHPUnit_Framework_TestCase', '\PHPUnit\Framework\TestCase');
}

class CurrencyConverterTest extends \PHPUnit_Framework_TestCase
{

    public function testValidAmountToWordsBG()
    {

        $translations = array(
            # Numbers
            0 => 'zero',
            1 => 'one',
            2 => 'two',
            3 => 'three',
            4 => 'four',
            5 => 'five',
            6 => 'six',
            7 => 'seven',
            8 => 'eight',
            9 => 'nine',
            10 => 'ten',
            11 => 'eleven',
            12 => 'twelve',
            13 => 'thirteen',
            14 => 'fourteen',
            15 => 'fifteen',
            16 => 'sixteen',
            17 => 'seventeen',
            18 => 'eighteen',
            19 => 'nineteen',
            20 => 'twenty',
            30 => 'thirty',
            40 => 'forty',
            50 => 'fifty',
            60 => 'sixty',
            70 => 'seventy',
            80 => 'eighty',
            90 => 'ninety',
            100 => ' hundred',
            200 => 'two hundred',
            300 => 'three hundred',
            1000 => 'one thousand',
            # Prefixes
            'tens' => 'ten',
            'hundreds' => 'hundred',
            'thousands' => 'thousands',
            'million' => 'million',
            'millions' => 'million',
            # Amounts
            'amount' => 'euro',
            'amounts' => 'euros',
            'cent' => 'cent',
            'cents' => 'cents',
            # Others
            'and' => ' and ',
        );

        $amounts = array(
            '309.89' => array('bg' => 'триста и девет лева и осемдесет и девет стотинки', 'en' => 'three hundred and nine euros and eighty-nine cents'),
            '163.20' => array('bg' => 'сто шестдесет и три лева и двадесет стотинки', 'en' => 'one hundred sixty-three euros and twenty cents'),
            '401.32' => array('bg' => 'четиристотин и един лева и тридесет и две стотинки', 'en' => 'four hundred and one euros and thirty-two cents'),
            '289.27' => array('bg' => 'двеста осемдесет и девет лева и двадесет и седем стотинки', 'en' => 'two hundred eighty-nine euros and twenty-seven cents'),
            '977.29' => array('bg' => 'деветстотин седемдесет и седем лева и двадесет и девет стотинки', 'en' => 'nine hundred seventy-seven euros and twenty-nine cents'),
            '772.56' => array('bg' => 'седемстотин седемдесет и два лева и петдесет и шест стотинки', 'en' => 'seven hundred seventy-two euros and fifty-six cents'),
            '319.20' => array('bg' => 'триста и деветнадесет лева и двадесет стотинки', 'en' => 'three hundred and nineteen euros and twenty cents'),
            '571.40' => array('bg' => 'петстотин седемдесет и един лева и четиридесет стотинки', 'en' => 'five hundred seventy-one euros and forty cents'),
            '765.23' => array('bg' => 'седемстотин шестдесет и пет лева и двадесет и три стотинки', 'en' => 'seven hundred sixty-five euros and twenty-three cents'),
            '896.17' => array('bg' => 'осемстотин деветдесет и шест лева и седемнадесет стотинки', 'en' => 'eight hundred ninety-six euros and seventeen cents'),
            '596.15' => array('bg' => 'петстотин деветдесет и шест лева и петнадесет стотинки', 'en' => 'five hundred ninety-six euros and fifteen cents'),
            '705.92' => array('bg' => 'седемстотин и пет лева и деветдесет и две стотинки', 'en' => 'seven hundred and five euros and ninety-two cents'),
            '348.48' => array('bg' => 'триста четиридесет и осем лева и четиридесет и осем стотинки', 'en' => 'three hundred forty-eight euros and forty-eight cents'),
            '309.77' => array('bg' => 'триста и девет лева и седемдесет и седем стотинки', 'en' => 'three hundred and nine euros and seventy-seven cents'),
            '106.45' => array('bg' => 'сто и шест лева и четиридесет и пет стотинки', 'en' => 'one hundred and six euros and forty-five cents'),
            '467.67' => array('bg' => 'четиристотин шестдесет и седем лева и шестдесет и седем стотинки', 'en' => 'four hundred sixty-seven euros and sixty-seven cents'),
            '403.78' => array('bg' => 'четиристотин и три лева и седемдесет и осем стотинки', 'en' => 'four hundred and three euros and seventy-eight cents'),
            '588.11' => array('bg' => 'петстотин осемдесет и осем лева и единадесет стотинки', 'en' => 'five hundred eighty-eight euros and eleven cents'),
            '425.69' => array('bg' => 'четиристотин двадесет и пет лева и шестдесет и девет стотинки', 'en' => 'four hundred twenty-five euros and sixty-nine cents'),
            '531.50' => array('bg' => 'петстотин тридесет и един лева и петдесет стотинки', 'en' => 'five hundred thirty-one euros and fifty cents'),
            '705.89' => array('bg' => 'седемстотин и пет лева и осемдесет и девет стотинки', 'en' => 'seven hundred and five euros and eighty-nine cents'),
            '606.94' => array('bg' => 'шестстотин и шест лева и деветдесет и четири стотинки', 'en' => 'six hundred and six euros and ninety-four cents'),
            '427.61' => array('bg' => 'четиристотин двадесет и седем лева и шестдесет и един стотинки', 'en' => 'four hundred twenty-seven euros and sixty-one cents'),
            '672.78' => array('bg' => 'шестстотин седемдесет и два лева и седемдесет и осем стотинки', 'en' => 'six hundred seventy-two euros and seventy-eight cents'),
            '127.56' => array('bg' => 'сто двадесет и седем лева и петдесет и шест стотинки', 'en' => 'one hundred twenty-seven euros and fifty-six cents'),
            '138.20' => array('bg' => 'сто тридесет и осем лева и двадесет стотинки', 'en' => 'one hundred thirty-eight euros and twenty cents'),
            '789.95' => array('bg' => 'седемстотин осемдесет и девет лева и деветдесет и пет стотинки', 'en' => 'seven hundred eighty-nine euros and ninety-five cents'),
            '666.63' => array('bg' => 'шестстотин шестдесет и шест лева и шестдесет и три стотинки', 'en' => 'six hundred sixty-six euros and sixty-three cents'),
            '245.53' => array('bg' => 'двеста четиридесет и пет лева и петдесет и три стотинки', 'en' => 'two hundred forty-five euros and fifty-three cents'),
            '762.90' => array('bg' => 'седемстотин шестдесет и два лева и деветдесет стотинки', 'en' => 'seven hundred sixty-two euros and ninety cents'),
            '383.48' => array('bg' => 'триста осемдесет и три лева и четиридесет и осем стотинки', 'en' => 'three hundred eighty-three euros and forty-eight cents'),
            '286.35' => array('bg' => 'двеста осемдесет и шест лева и тридесет и пет стотинки', 'en' => 'two hundred eighty-six euros and thirty-five cents'),
            '835.55' => array('bg' => 'осемстотин тридесет и пет лева и петдесет и пет стотинки', 'en' => 'eight hundred thirty-five euros and fifty-five cents'),
            '449.89' => array('bg' => 'четиристотин четиридесет и девет лева и осемдесет и девет стотинки', 'en' => 'four hundred forty-nine euros and eighty-nine cents'),
            '786.94' => array('bg' => 'седемстотин осемдесет и шест лева и деветдесет и четири стотинки', 'en' => 'seven hundred eighty-six euros and ninety-four cents'),
            '210.69' => array('bg' => 'двеста и десет лева и шестдесет и девет стотинки', 'en' => 'two hundred and ten euros and sixty-nine cents'),
            '771.38' => array('bg' => 'седемстотин седемдесет и един лева и тридесет и осем стотинки', 'en' => 'seven hundred seventy-one euros and thirty-eight cents'),
            '777.20' => array('bg' => 'седемстотин седемдесет и седем лева и двадесет стотинки', 'en' => 'seven hundred seventy-seven euros and twenty cents'),
            '873.80' => array('bg' => 'осемстотин седемдесет и три лева и осемдесет стотинки', 'en' => 'eight hundred seventy-three euros and eighty cents'),
            '210.40' => array('bg' => 'двеста и десет лева и четиридесет стотинки', 'en' => 'two hundred and ten euros and forty cents'),
            '728.76' => array('bg' => 'седемстотин двадесет и осем лева и седемдесет и шест стотинки', 'en' => 'seven hundred twenty-eight euros and seventy-six cents'),
            '620.74' => array('bg' => 'шестстотин и двадесет лева и седемдесет и четири стотинки', 'en' => 'six hundred and twenty euros and seventy-four cents'),
            '418.64' => array('bg' => 'четиристотин и осемнадесет лева и шестдесет и четири стотинки', 'en' => 'four hundred and eighteen euros and sixty-four cents'),
            '964.22' => array('bg' => 'деветстотин шестдесет и четири лева и двадесет и две стотинки', 'en' => 'nine hundred sixty-four euros and twenty-two cents'),
            '480.45' => array('bg' => 'четиристотин и осемдесет лева и четиридесет и пет стотинки', 'en' => 'four hundred and eighty euros and forty-five cents'),
            '652.28' => array('bg' => 'шестстотин петдесет и два лева и двадесет и осем стотинки', 'en' => 'six hundred fifty-two euros and twenty-eight cents'),
            '998.39' => array('bg' => 'деветстотин деветдесет и осем лева и тридесет и девет стотинки', 'en' => 'nine hundred ninety-eight euros and thirty-nine cents'),
            '444.90' => array('bg' => 'четиристотин четиридесет и четири лева и деветдесет стотинки', 'en' => 'four hundred forty-four euros and ninety cents'),
            '704.19' => array('bg' => 'седемстотин и четири лева и деветнадесет стотинки', 'en' => 'seven hundred and four euros and nineteen cents'),
            '649.56' => array('bg' => 'шестстотин четиридесет и девет лева и петдесет и шест стотинки', 'en' => 'six hundred forty-nine euros and fifty-six cents'),
            '585.70' => array('bg' => 'петстотин осемдесет и пет лева и седемдесет стотинки', 'en' => 'five hundred eighty-five euros and seventy cents'),
            '226.22' => array('bg' => 'двеста двадесет и шест лева и двадесет и две стотинки', 'en' => 'two hundred twenty-six euros and twenty-two cents'),
            '274.73' => array('bg' => 'двеста седемдесет и четири лева и седемдесет и три стотинки', 'en' => 'two hundred seventy-four euros and seventy-three cents'),
            '386.33' => array('bg' => 'триста осемдесет и шест лева и тридесет и три стотинки', 'en' => 'three hundred eighty-six euros and thirty-three cents'),
            '756.42' => array('bg' => 'седемстотин петдесет и шест лева и четиридесет и две стотинки', 'en' => 'seven hundred fifty-six euros and forty-two cents'),
            '987.88' => array('bg' => 'деветстотин осемдесет и седем лева и осемдесет и осем стотинки', 'en' => 'nine hundred eighty-seven euros and eighty-eight cents'),
            '765.83' => array('bg' => 'седемстотин шестдесет и пет лева и осемдесет и три стотинки', 'en' => 'seven hundred sixty-five euros and eighty-three cents'),
            '538.35' => array('bg' => 'петстотин тридесет и осем лева и тридесет и пет стотинки', 'en' => 'five hundred thirty-eight euros and thirty-five cents'),
            '386.21' => array('bg' => 'триста осемдесет и шест лева и двадесет и един стотинки', 'en' => 'three hundred eighty-six euros and twenty-one cents'),
            '699.68' => array('bg' => 'шестстотин деветдесет и девет лева и шестдесет и осем стотинки', 'en' => 'six hundred ninety-nine euros and sixty-eight cents'),
            '152.25' => array('bg' => 'сто петдесет и два лева и двадесет и пет стотинки', 'en' => 'one hundred fifty-two euros and twenty-five cents'),
            '880.35' => array('bg' => 'осемстотин и осемдесет лева и тридесет и пет стотинки', 'en' => 'eight hundred and eighty euros and thirty-five cents'),
            '149.17' => array('bg' => 'сто четиридесет и девет лева и седемнадесет стотинки', 'en' => 'one hundred forty-nine euros and seventeen cents'),
            '939.34' => array('bg' => 'деветстотин тридесет и девет лева и тридесет и четири стотинки', 'en' => 'nine hundred thirty-nine euros and thirty-four cents'),
            '911.70' => array('bg' => 'деветстотин и единадесет лева и седемдесет стотинки', 'en' => 'nine hundred and eleven euros and seventy cents'),
            '286.10' => array('bg' => 'двеста осемдесет и шест лева и десет стотинки', 'en' => 'two hundred eighty-six euros and ten cents'),
            '721.70' => array('bg' => 'седемстотин двадесет и един лева и седемдесет стотинки', 'en' => 'seven hundred twenty-one euros and seventy cents'),
            '581.61' => array('bg' => 'петстотин осемдесет и един лева и шестдесет и един стотинки', 'en' => 'five hundred eighty-one euros and sixty-one cents'),
            '115.96' => array('bg' => 'сто и петнадесет лева и деветдесет и шест стотинки', 'en' => 'one hundred and fifteen euros and ninety-six cents'),
            '332.34' => array('bg' => 'триста тридесет и два лева и тридесет и четири стотинки', 'en' => 'three hundred thirty-two euros and thirty-four cents'),
            '977.64' => array('bg' => 'деветстотин седемдесет и седем лева и шестдесет и четири стотинки', 'en' => 'nine hundred seventy-seven euros and sixty-four cents'),
            '300.26' => array('bg' => 'триста лева и двадесет и шест стотинки', 'en' => 'three hundred euros and twenty-six cents'),
            '240.79' => array('bg' => 'двеста и четиридесет лева и седемдесет и девет стотинки', 'en' => 'two hundred and forty euros and seventy-nine cents'),
            '794.82' => array('bg' => 'седемстотин деветдесет и четири лева и осемдесет и две стотинки', 'en' => 'seven hundred ninety-four euros and eighty-two cents'),
            '691.64' => array('bg' => 'шестстотин деветдесет и един лева и шестдесет и четири стотинки', 'en' => 'six hundred ninety-one euros and sixty-four cents'),
            '772.20' => array('bg' => 'седемстотин седемдесет и два лева и двадесет стотинки', 'en' => 'seven hundred seventy-two euros and twenty cents'),
            '162.91' => array('bg' => 'сто шестдесет и два лева и деветдесет и един стотинки', 'en' => 'one hundred sixty-two euros and ninety-one cents'),
            '545.30' => array('bg' => 'петстотин четиридесет и пет лева и тридесет стотинки', 'en' => 'five hundred forty-five euros and thirty cents'),
            '538.82' => array('bg' => 'петстотин тридесет и осем лева и осемдесет и две стотинки', 'en' => 'five hundred thirty-eight euros and eighty-two cents'),
            '871.64' => array('bg' => 'осемстотин седемдесет и един лева и шестдесет и четири стотинки', 'en' => 'eight hundred seventy-one euros and sixty-four cents'),
            '555.10' => array('bg' => 'петстотин петдесет и пет лева и десет стотинки', 'en' => 'five hundred fifty-five euros and ten cents'),
            '260.51' => array('bg' => 'двеста и шестдесет лева и петдесет и един стотинки', 'en' => 'two hundred and sixty euros and fifty-one cents'),
            '295.93' => array('bg' => 'двеста деветдесет и пет лева и деветдесет и три стотинки', 'en' => 'two hundred ninety-five euros and ninety-three cents'),
            '372.88' => array('bg' => 'триста седемдесет и два лева и осемдесет и осем стотинки', 'en' => 'three hundred seventy-two euros and eighty-eight cents'),
            '293.80' => array('bg' => 'двеста деветдесет и три лева и осемдесет стотинки', 'en' => 'two hundred ninety-three euros and eighty cents'),
            '616.22' => array('bg' => 'шестстотин и шестнадесет лева и двадесет и две стотинки', 'en' => 'six hundred and sixteen euros and twenty-two cents'),
            '635.73' => array('bg' => 'шестстотин тридесет и пет лева и седемдесет и три стотинки', 'en' => 'six hundred thirty-five euros and seventy-three cents'),
            '852.49' => array('bg' => 'осемстотин петдесет и два лева и четиридесет и девет стотинки', 'en' => 'eight hundred fifty-two euros and forty-nine cents'),
            '954.62' => array('bg' => 'деветстотин петдесет и четири лева и шестдесет и две стотинки', 'en' => 'nine hundred fifty-four euros and sixty-two cents'),
            '487.17' => array('bg' => 'четиристотин осемдесет и седем лева и седемнадесет стотинки', 'en' => 'four hundred eighty-seven euros and seventeen cents'),
            '433.95' => array('bg' => 'четиристотин тридесет и три лева и деветдесет и пет стотинки', 'en' => 'four hundred thirty-three euros and ninety-five cents'),
            '282.22' => array('bg' => 'двеста осемдесет и два лева и двадесет и две стотинки', 'en' => 'two hundred eighty-two euros and twenty-two cents'),
            '509.46' => array('bg' => 'петстотин и девет лева и четиридесет и шест стотинки', 'en' => 'five hundred and nine euros and forty-six cents'),
            '547.12' => array('bg' => 'петстотин четиридесет и седем лева и дванадесет стотинки', 'en' => 'five hundred forty-seven euros and twelve cents'),
            '365.36' => array('bg' => 'триста шестдесет и пет лева и тридесет и шест стотинки', 'en' => 'three hundred sixty-five euros and thirty-six cents'),
            '241.81' => array('bg' => 'двеста четиридесет и един лева и осемдесет и един стотинки', 'en' => 'two hundred forty-one euros and eighty-one cents'),
            '536.36' => array('bg' => 'петстотин тридесет и шест лева и тридесет и шест стотинки', 'en' => 'five hundred thirty-six euros and thirty-six cents'),
            '573.80' => array('bg' => 'петстотин седемдесет и три лева и осемдесет стотинки', 'en' => 'five hundred seventy-three euros and eighty cents'),
            '206.68' => array('bg' => 'двеста и шест лева и шестдесет и осем стотинки', 'en' => 'two hundred and six euros and sixty-eight cents'),
            '502.40' => array('bg' => 'петстотин и два лева и четиридесет стотинки', 'en' => 'five hundred and two euros and forty cents')
        );

        foreach ($amounts AS $amount => $translation) {
            $this->assertEquals($translation['bg'], CurrencyConverter::convertToText($amount, array()));
            $this->assertEquals($translation['en'], CurrencyConverter::convertToText($amount, $translations, 'en'));
        }
    }

}
